import type { IconType } from 'react-icons';
import {
	LuBookOpen,
	LuBuilding2,
	LuCalculator,
	LuCalendar,
	LuCalendarOff,
	LuChartBar,
	LuClipboardList,
	LuCreditCard,
	LuFileSpreadsheet,
	LuFolderOpen,
	LuGraduationCap,
	LuInbox,
	LuLayoutDashboard,
	LuMail,
	LuMegaphone,
	LuMusic2,
	LuSettings,
	LuShieldAlert,
	LuUpload,
	LuUser,
	LuUserCog,
	LuUsers,
} from 'react-icons/lu';

/**
 * Central source for navigation labels (sidebar, breadcrumbs, page titles, command palette).
 * Use these constants everywhere to stay DRY and avoid typos like "Lestypen" vs "Lessoorten".
 */
export const NAV_LABELS = {
	agenda: 'Agenda',
	dashboard: 'Dashboard',
	users: 'Gebruikers',
	lessonTypes: 'Lessoorten',
	projects: 'Projecten',
	settings: 'Instellingen',
	teachers: 'Docenten',
	availability: 'Beschikbaarheid',
	myProfile: 'Mijn profiel',
	myAvailability: 'Mijn beschikbaarheid',
	myStatistics: 'Mijn statistieken',
	students: 'Leerlingen',
	myStudents: 'Mijn leerlingen',
	agreements: 'Overeenkomsten',
	lessonGroups: 'Groepslessen',
	signupRequests: 'Aanmeldingen',
	trialLessons: 'Proeflessen',
	myTrial: 'Mijn proefles',
	reports: 'Rapportage',
	accounting: 'Boekhouding',
	accountingSettings: 'Boekhouding-instellingen',
	dataImport: 'Data-import',
	subscriptions: 'Facturatie',
	incasso: 'Incasso',
	mandaten: 'Mandaten',
	invoices: 'Facturen',
	myInvoices: 'Mijn facturen',
	noLessonPeriods: 'Lesvrije periodes',
	emailTemplates: 'E-mailtemplates',
	announcements: 'Nieuwsberichten',
	manual: 'Handleiding',
	accountProfile: 'Profiel',
	accountAppearance: 'Weergave',
	accountDanger: 'Account',
} as const;

export type NavLabelKey = keyof typeof NAV_LABELS;

/**
 * Icon per nav item (sidebar, PageHeader, etc.). Single source of truth for nav icons.
 */
export const NAV_ICONS: Record<NavLabelKey, IconType> = {
	agenda: LuCalendar,
	dashboard: LuLayoutDashboard,
	users: LuUserCog,
	lessonTypes: LuMusic2,
	projects: LuFolderOpen,
	settings: LuSettings,
	teachers: LuGraduationCap,
	availability: LuCalendar,
	myProfile: LuUser,
	myAvailability: LuCalendar,
	myStatistics: LuChartBar,
	students: LuUsers,
	myStudents: LuUsers,
	agreements: LuClipboardList,
	lessonGroups: LuUsers,
	signupRequests: LuInbox,
	trialLessons: LuGraduationCap,
	myTrial: LuGraduationCap,
	reports: LuChartBar,
	accounting: LuCalculator,
	accountingSettings: LuCalculator,
	dataImport: LuUpload,
	subscriptions: LuCreditCard,
	incasso: LuFileSpreadsheet,
	mandaten: LuBuilding2,
	noLessonPeriods: LuCalendarOff,
	emailTemplates: LuMail,
	announcements: LuMegaphone,
	manual: LuBookOpen,
	accountProfile: LuUser,
	accountAppearance: LuSettings,
	accountDanger: LuShieldAlert,
};
